name: deployment

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'

env:
  MATTERS_SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Build
        run: npm run build

      # === `develop` branch ===
      - name: Deploy (devlop)
        if: github.ref == 'refs/heads/develop'
        run: npm run upload:dev

      # === `master` branch ===
      - name: Deploy (production)
        if: github.ref == 'refs/heads/master'
        run: npm run upload:prod

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: matters-email
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
