name: Deployment

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'

env:
  MATTERS_SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.16'

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm run lint

      - name: Build
        run: npm run build

      # === `develop` branch ===
      - name: Upload (devlop)
        if: github.ref == 'refs/heads/develop'
        run: npm run upload:dev

      # === `master` branch ===
      - name: Upload (production)
        if: github.ref == 'refs/heads/master'
        run: npm run upload:prod

      - name: Slack Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: matters-email
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
